### ISSUE TITLE
Build fails on CoreOS 1800.6.0

### ISSUE THREAD

**Issue by 12wrigja** [lorenz/torcx-zfs#1]
I'm trying to use this repository to build ZOL version  0.7.9 for CoreOS version 1800.6.0. After eventually getting a copy of the developer image to import into docker, I mounted the directory and ran the build script. It seems it fails when building autoconf-2.69.

As the emerge failure suggested, here are some useful files:
 - The original build logs: https://gist.github.com/12wrigja/ef30ef10e27b46700157df88d339e505
 - the output from emerge info: https://gist.github.com/12wrigja/c3c876f65a7430998f108175d1f579d4
 - the output from emerge -pqv (inline):
[ebuild  N    ] sys-devel/autoconf-2.69  USE="-emacs" 

Are you still using this repository? I originally found it via https://lorenz.brun.one/setting-up-zfs/, but the readme doesn't mention recent versions of coreos at all.

**Comment by lorenz** [comment]
This is because of https://github.com/coreos/bugs/issues/2369. I have a hack that works around that by basically injecting a statically compiled Perl into the build environment. Problem is that this is just an opaque hacked binary and I don't really like committing these to OSS repos. I'm currently busy with uni work, I'll see if I can put this workaround in publishable condition in like a week or so.

EDIT: And yes, I still actively use this setup on my own servers. But I have an internal GitLab where most of the work is done and when it is nice and generally usable I'll push it out to GitHub.

**Comment by 12wrigja** [comment]
Thanks Lorenz - any workarounds are appreciated. I'm trying to setup something similar and was inspired by your blog post. For now, I've frozen that particular machine at 1745.7.0, where this compilation still works, and that's unblocked me.

**Comment by lorenz** [comment]
I have published my newest patching system which is actually suprisingly simple and doesn't rely on hacked-together binaries anymore. It might have broken pre-1745 builds though since they don't contain an embedded Perl yet (so nothing to rebuild). But all newer CoreOS versions should now work again.
